#Configuração Separador inteligente SmartHopper
author: ElderBR
discord: ElderBR#5398
#Versão do plugin
version: 4.0.6
# Verifica se os itens estão atualizados
item atualizado: true
#Verifica se os grupos estão atualizados
grupo atualizado: true
# Usa textura personalizada para os botões de navegação dos itens do grupo
# link texture pack http://elderbr.com/minecraft/textures/SmartHopper.zip
isUseTexture: true;
#Adminsitradores é responsável por adicionar ou remover operadores
#Fica responsável por adicionar, alterar ou remover grupos
adm:
  - ElderBR
#Linguagens disponível
lang:
  - pt_br
  - pt_pt