name: SmartHopper
version: 4.1.0
main: mc.elderbr.smarthopper.MainSmartHopper
api-version: 1.21
authors: [ ElderBR ]
commands:
  item:
    usage: /item <código>
    description: Mostra o número do ID do material
  traducaoitem:
    usage: /traducaoitem <codigo> <traducao>
    description: Adicionar tradução ao item
  grupo:
    aliases: group
    usage: /grupo <código>
    description: Mostra o número do Grupo do material
  traducaogrupo:
    usage: /traducaogrupo <codigo> <traducao>
    description: Adicionar tradução para o grupo
  addgrupo:
    description: Adicionar novo grupo
  removegrupo:
    description: Remover grupo existente
  gruponame:
    description: Gera o arquivo grupo_name.yml com todos os nomes dos grupos
  addAdm:
      description: Adiciona Administrador para o SmartHopper
  removeradm:
    description: Remove o jogador do Adm do SmartHopper
  tutorial:
    description: Vídeo que mostra como usar o SmartHopper
  reload:
    description: Carrega os itens, grupos e tradução
  useTexture:
    description: Opção para carregar a textura do Smart Hopper
    usage: useTexture [ true | false ]