name: SmartHopper
version: 4.0.0
main: mc.elderbr.smarthopper.MainSmartHopper
api-version: 1.18
authors: [ ElderBR ]
commands:
  item:
    description: Mostra o número do ID do material
  grupo:
    description: Mostra o número do Grupo do material
  addgrupo:
    description: Adicionar novo grupo
  removegrupo:
    description: Remover grupo existente
  addAdm:
      description: Adiciona Administrador para o SmartHopper
  removerAdm:
    description: Adiciona Operador para o SmartHopper
  livro:
    aliases: [ book, livro ]
    description: Recebe um livro com os nomes de todos os grupos