name: Build SmartHopper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create version directory if not exists
        run: mkdir -p version

      - name: Copy JAR to version directory
        run: |
          VERSION=$(./gradlew -q printVersion)
          cp build/libs/SmartHopper-v*.jar version/SmartHopper-v$VERSION.jar

      - name: Upload the JAR (optional)
        uses: actions/upload-artifact@v2
        with:
          name: SmartHopper-JAR
          path: version/SmartHopper-v*.jar