name: Java CI with Gradle

on:
  push:
    branches:
      - main  # O workflow será disparado em pushes para a branch main
  pull_request:
    branches:
      - main  # Também será disparado quando houver pull requests para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  # Use a versão do Java que você precisa

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate JAR
      run: ./gradlew jar

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-jar
        path: build/libs/*.jar  # Caminho para o arquivo jar gerado
